language: ruby
cache: bundler

before_script: rake db:create RACK_ENV=test

rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.1

notifications:
    email:
        recipients:
            - sndicate_build_errors@mailinator.com
        on_failure: change
        on_success: never
